spring:
  config:
    location: testingFileConfiguration
  application:
    name: config-updater
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres